### ISSUE TITLE
Compatiblity with HAML

### ISSUE THREAD

**Issue by jbpfran** [bridgetownrb/bridgetown-view-component#6]
Hello,

I tried this plugins in collaboration with the bridgetown-haml plugins to build the views in HAML.

I got the following error :
```
There was an error when building the site:
ViewComponent::TemplateError: Couldn't find a template file or inline render method for Shared::Header
```
when the template file is header.haml
However it works correctly with hearder.erb

I tried initializing the view-component plugin before and after the haml plugin but it didn't change the result.

Thanks for your help.

**Comment by jaredcwhite** [comment]
Closing because we're deprecating Haml support in Bridgetown 2.0. Recommend a switch to ERB or Serbea.
